CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN');
CREATE TYPE "PrintType" AS ENUM ('BW', 'COLOR');
CREATE TYPE "PaperSize" AS ENUM ('A4', 'A3');
CREATE TYPE "SideType" AS ENUM ('SINGLE', 'DOUBLE');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PAID', 'PRINTING', 'PRINTED', 'FAILED');
CREATE TYPE "PrintJobStatus" AS ENUM ('WAITING', 'PRINTING', 'PRINTED');
CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"password" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'USER',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Order" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"fileUrl" TEXT NOT NULL,"filePath" TEXT NOT NULL,"fileName" TEXT NOT NULL,"pages" INTEGER NOT NULL,"copies" INTEGER NOT NULL,"printType" "PrintType" NOT NULL,"paperSize" "PaperSize" NOT NULL,"sideType" "SideType" NOT NULL,"amount" INTEGER NOT NULL,"paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"orderStatus" "OrderStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Order_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"razorpayOrderId" TEXT NOT NULL,"razorpayPaymentId" TEXT,"amount" INTEGER NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Pricing" ("id" TEXT NOT NULL,"bwPrice" INTEGER NOT NULL DEFAULT 2,"colorPrice" INTEGER NOT NULL DEFAULT 10,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Pricing_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PrintJob" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"status" "PrintJobStatus" NOT NULL DEFAULT 'WAITING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PrintJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "Order_userId_createdAt_idx" ON "Order"("userId", "createdAt");
CREATE INDEX "Order_orderStatus_createdAt_idx" ON "Order"("orderStatus", "createdAt");
CREATE UNIQUE INDEX "Payment_orderId_key" ON "Payment"("orderId");
CREATE UNIQUE INDEX "Payment_razorpayOrderId_key" ON "Payment"("razorpayOrderId");
CREATE UNIQUE INDEX "PrintJob_orderId_key" ON "PrintJob"("orderId");
ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PrintJob" ADD CONSTRAINT "PrintJob_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
INSERT INTO "Pricing" ("id","bwPrice","colorPrice","updatedAt") VALUES ('default-pricing',2,10,CURRENT_TIMESTAMP);
